# Pipeline Overview

This notebook implements the full data preparation pipeline for the Construction Delay Risk Prediction System. The goal of this stage is to transform the raw dataset into a clean, structured, and machine‑learning‑ready format. The pipeline follows a modular architecture, where each step is handled by a dedicated component within the `src` directory. This ensures clarity, maintainability, and reproducibility across the entire workflow.

The preparation pipeline consists of the following stages:

# 1. Data Cleaning
The dataset is first passed through the cleaning module, which:
- Fixes incorrect or inconsistent data types  
- Handles missing values using transparent rules  
- Removes or flags invalid rows (e.g., negative durations or impossible values)  
- Ensures the dataset is structurally sound before further processing  

This step guarantees that the data entering the model is reliable and free from basic quality issues.

# 2. Categorical Encoding
Categorical features are transformed into numerical representations using Label Encoding.  
This step:
- Converts string‑based categories into integer labels  
- Stores the fitted encoders for later use during inference  
- Ensures consistency between training and deployment environments  

# 3. Numerical Scaling
Numerical features are standardized using a scaling technique to ensure:
- All numeric columns share a similar range  
- The model is not biased toward features with larger magnitudes  
- Training becomes more stable and efficient  

The fitted scaler is also preserved for use during prediction.

# 4. Dataset Splitting
The cleaned and transformed dataset is divided into:
- **Training set
- **Validation set
- **Test set

This split supports:
- Model training  
- Hyperparameter tuning  
- Final unbiased evaluation  

Optional stratification ensures that the target variable maintains its distribution across all splits.

In [80]:
import sys
import os

# Get the project root (one level above the notebook directory)
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))

# Add project root to Python path
if project_root not in sys.path:
    sys.path.append(project_root)

print("Project root added to Python path:", project_root)

Project root added to Python path: c:\Users\olive\Desktop\My ML Material\CONSTRUCTION DELAY RISK PREDICTION SYSTEM\CDRPS

In [81]:
import pandas as pd
from src.ingestion.file_loader import load_file

# Path to your dataset
dataset_path = r"C:\Users\olive\Desktop\My ML Material\CONSTRUCTION DELAY RISK PREDICTION SYSTEM\archive(1)\Road Constuction Delay Survey.csv"

# Load raw dataset
df_raw = load_file(dataset_path)

df_raw.head()

,Respondent Number,Category 1: Materials,Category 1: Materials.1,Category 1: Materials.2,Category 1: Materials.3,Category 1: Materials.4,Category 2: Labor and Equipment,Category 2: Labor and Equipment.1,Category 2: Labor and Equipment.2,Category 2: Labor and Equipment.3,...,Category 8: Scope of work.3,Category 9: External issues,Category 9: External issues .1,Category 9: External issues .2,Respondant Information,Respondant Information.1,Respondant Information.2,Respondant Information.3,Respondant Information.4,Respondant Information.5
0,NaN,1.Delay in delivering material to construction...,2.Monopoly of material by some suppliers,3.Prices fluctuation,4.Types of material availability at local market,5.Lack of consultants knowledge of available ...,6.Low productivity,7.Poor work execution,8.Shortage of laborers,9.Mistakes happens during construction phase,...,41.Rework due to error in execution,42.Weather conditions,43.Accidents during construction,44.Delay in getting NOCs from different govern...,Type of Organization,Respondents designation,Indicate the highest formal qualification,How often do you experience cost overrun,Location of organization,Relevant working experience
1,1.0,1,1,1,1,1,1,1,1,1,...,1,2,2,3,1,2,2,2,3,5
2,2.0,2,5,3,2,3,2,2,2,3,...,3,1,1,4,1,3,2,3,3,3
3,3.0,1,2,1,1,2,2,1,2,1,...,2,1,1,4,1,2,2,1,2,4
4,4.0,2,2,3,3,2,2,3,4,4,...,3,4,3,3,1,3,1,1,3,4

In [82]:
from src.preparation.cleaning import clean_dataset
from src.preparation.encoding import encode_categorical, scale_numerical
from src.preparation.splitter import split_dataset

In [83]:
numeric_columns = df_encoded.select_dtypes(include=["int64", "float64"]).columns.tolist()

In [84]:
numeric_columns = [
    "Respondent Number",
]

categorical_columns = [
    # List survey response columns
]

datetime_columns = [
    # e.g., "start_date", "end_date"
]

non_negative_columns = [
    # e.g., "planned_duration", "actual_duration"
]

# Target column (exclude from scaling)
target_column = "How often do you experience cost overrun"

In [85]:
df_clean = clean_dataset(
    df_raw,
    numeric_columns=numeric_columns,
    datetime_columns=datetime_columns,
    non_negative_columns=non_negative_columns,
    drop_threshold=0.5,
)

df_clean.head()

,Respondent Number,Category 1: Materials,Category 1: Materials.1,Category 1: Materials.2,Category 1: Materials.3,Category 1: Materials.4,Category 2: Labor and Equipment,Category 2: Labor and Equipment.1,Category 2: Labor and Equipment.2,Category 2: Labor and Equipment.3,...,Category 8: Scope of work.3,Category 9: External issues,Category 9: External issues .1,Category 9: External issues .2,Respondant Information,Respondant Information.1,Respondant Information.2,Respondant Information.3,Respondant Information.4,Respondant Information.5
0,NaN,1.Delay in delivering material to construction...,2.Monopoly of material by some suppliers,3.Prices fluctuation,4.Types of material availability at local market,5.Lack of consultants knowledge of available ...,6.Low productivity,7.Poor work execution,8.Shortage of laborers,9.Mistakes happens during construction phase,...,41.Rework due to error in execution,42.Weather conditions,43.Accidents during construction,44.Delay in getting NOCs from different govern...,Type of Organization,Respondents designation,Indicate the highest formal qualification,How often do you experience cost overrun,Location of organization,Relevant working experience
1,1.0,1,1,1,1,1,1,1,1,1,...,1,2,2,3,1,2,2,2,3,5
2,2.0,2,5,3,2,3,2,2,2,3,...,3,1,1,4,1,3,2,3,3,3
3,3.0,1,2,1,1,2,2,1,2,1,...,2,1,1,4,1,2,2,1,2,4
4,4.0,2,2,3,3,2,2,3,4,4,...,3,4,3,3,1,3,1,1,3,4

In [86]:
df_encoded, label_encoders = encode_categorical(
    df_clean,
    categorical_columns=categorical_columns,
)

df_encoded.head()

,Respondent Number,Category 1: Materials,Category 1: Materials.1,Category 1: Materials.2,Category 1: Materials.3,Category 1: Materials.4,Category 2: Labor and Equipment,Category 2: Labor and Equipment.1,Category 2: Labor and Equipment.2,Category 2: Labor and Equipment.3,...,Category 8: Scope of work.3,Category 9: External issues,Category 9: External issues .1,Category 9: External issues .2,Respondant Information,Respondant Information.1,Respondant Information.2,Respondant Information.3,Respondant Information.4,Respondant Information.5
0,NaN,1.Delay in delivering material to construction...,2.Monopoly of material by some suppliers,3.Prices fluctuation,4.Types of material availability at local market,5.Lack of consultants knowledge of available ...,6.Low productivity,7.Poor work execution,8.Shortage of laborers,9.Mistakes happens during construction phase,...,41.Rework due to error in execution,42.Weather conditions,43.Accidents during construction,44.Delay in getting NOCs from different govern...,Type of Organization,Respondents designation,Indicate the highest formal qualification,How often do you experience cost overrun,Location of organization,Relevant working experience
1,1.0,1,1,1,1,1,1,1,1,1,...,1,2,2,3,1,2,2,2,3,5
2,2.0,2,5,3,2,3,2,2,2,3,...,3,1,1,4,1,3,2,3,3,3
3,3.0,1,2,1,1,2,2,1,2,1,...,2,1,1,4,1,2,2,1,2,4
4,4.0,2,2,3,3,2,2,3,4,4,...,3,4,3,3,1,3,1,1,3,4

In [87]:
# Auto-detect numeric columns from df_encoded (exclude target)
numeric_columns_to_scale = df_encoded.select_dtypes(include=["number"]).columns.tolist()

# Remove target from scaling list
if target_column in numeric_columns_to_scale:
    numeric_columns_to_scale.remove(target_column)

print(f"Columns to scale ({len(numeric_columns_to_scale)}): {numeric_columns_to_scale[:5]}...")

df_scaled, scaler = scale_numerical(
    df_encoded,
    numeric_columns=numeric_columns_to_scale,
)

print(f"✓ Scaled dataset: {df_scaled.shape}")
df_scaled.head()

Columns to scale (1): ['Respondent Number ']...
✓ Scaled dataset: (144, 51)

,Respondent Number,Category 1: Materials,Category 1: Materials.1,Category 1: Materials.2,Category 1: Materials.3,Category 1: Materials.4,Category 2: Labor and Equipment,Category 2: Labor and Equipment.1,Category 2: Labor and Equipment.2,Category 2: Labor and Equipment.3,...,Category 8: Scope of work.3,Category 9: External issues,Category 9: External issues .1,Category 9: External issues .2,Respondant Information,Respondant Information.1,Respondant Information.2,Respondant Information.3,Respondant Information.4,Respondant Information.5
0,NaN,1.Delay in delivering material to construction...,2.Monopoly of material by some suppliers,3.Prices fluctuation,4.Types of material availability at local market,5.Lack of consultants knowledge of available ...,6.Low productivity,7.Poor work execution,8.Shortage of laborers,9.Mistakes happens during construction phase,...,41.Rework due to error in execution,42.Weather conditions,43.Accidents during construction,44.Delay in getting NOCs from different govern...,Type of Organization,Respondents designation,Indicate the highest formal qualification,How often do you experience cost overrun,Location of organization,Relevant working experience
1,-1.719981,1,1,1,1,1,1,1,1,1,...,1,2,2,3,1,2,2,2,3,5
2,-1.695756,2,5,3,2,3,2,2,2,3,...,3,1,1,4,1,3,2,3,3,3
3,-1.671530,1,2,1,1,2,2,1,2,1,...,2,1,1,4,1,2,2,1,2,4
4,-1.647305,2,2,3,3,2,2,3,4,4,...,3,4,3,3,1,3,1,1,3,4

In [88]:
print("Numeric columns list:", numeric_columns)
print("Columns in df_encoded:", df_encoded.columns.tolist())

missing = [col for col in numeric_columns if col not in df_encoded.columns]
print("Missing numeric columns:", missing)

Numeric columns list: ['Respondent Number']
Columns in df_encoded: ['Respondent Number ', 'Category 1: Materials', 'Category 1: Materials.1', 'Category 1: Materials.2', 'Category 1: Materials.3', 'Category 1: Materials.4', 'Category 2: Labor and Equipment', 'Category 2: Labor and Equipment.1', 'Category 2: Labor and Equipment.2', 'Category 2: Labor and Equipment.3', 'Category 2: Labor and Equipment.4', 'Category 2: Labor and Equipment.5', 'Category 2: Labor and Equipment.6', 'Category 2: Labor and Equipment.7', 'Category 3: Financing', 'Category 3: Financing.1', 'Category 3: Financing.2', 'Category 3: Financing.3', 'Category 3: Financing.4', 'Category 4: Design and Documentation', 'Category 4: Design and Documentation.1', 'Category 4: Design and Documentation.2', 'Category 4: Design and Documentation.3', 'Category 4: Design and Documentation.4', 'Category 4: Design and Documentation.5', 'Category 5: Management and Organization ', 'Category 5: Management and Organization .1', 'Category 5: Management and Organization .2', 'Category 5: Management and Organization .3', 'Category 5: Management and Organization .4', 'Category 5: Management and Organization .5', 'Category 6: Schedule ', 'Category 6: Schedule .1', 'Category 7: Contractual issues ', 'Category 7: Contractual issues .1', 'Category 7: Contractual issues .2', 'Category 7: Contractual issues .3', 'Category 7: Contractual issues .4', 'Category 8: Scope of work', 'Category 8: Scope of work.1', 'Category 8: Scope of work.2', 'Category 8: Scope of work.3', 'Category 9: External issues ', 'Category 9: External issues .1', 'Category 9: External issues .2', 'Respondant Information', 'Respondant Information.1', 'Respondant Information.2', 'Respondant Information.3', 'Respondant Information.4', 'Respondant Information.5']
Missing numeric columns: ['Respondent Number']

In [89]:
# Since target column was dropped during cleaning, use a survey column as proxy target
# For demo: use "Respondant Information.3" (cost overrun frequency)
target_column = "Respondant Information.3"

if target_column not in df_scaled.columns:
    print(f"Target column '{target_column}' not found in df_scaled")
    print(f"Available columns: {df_scaled.columns.tolist()}")
else:
    X_train, X_val, X_test, y_train, y_val, y_test = split_dataset(
        df_scaled,
        target_column=target_column,
        test_size=0.2,
        val_size=0.1,
        random_state=42,
        stratify=False,  # Disable stratification due to class imbalance
    )

    print(f"✓ Training set: {X_train.shape}")
    print(f"✓ Validation set: {X_val.shape}")
    print(f"✓ Test set: {X_test.shape}")
    print(f"\nTarget distribution in training set:\n{y_train.value_counts().sort_index()}")

✓ Training set: (115, 50)
✓ Validation set: (3, 50)
✓ Test set: (26, 50)

Target distribution in training set:
Respondant Information.3
1                                           53
2                                           59
3                                            2
How often do you experience cost overrun     1
Name: count, dtype: int64

In [90]:
print("Training set:", X_train.shape, y_train.shape)
print("Validation set:", X_val.shape, y_val.shape)
print("Test set:", X_test.shape, y_test.shape)

Training set: (115, 50) (115,)
Validation set: (3, 50) (3,)
Test set: (26, 50) (26,)

# Purpose of This Notebook

This notebook orchestrates the entire preparation pipeline — from raw data to ready‑to‑model datasets. It ensures that every transformation is applied consistently, reproducibly, and in alignment with the system’s functional specification. The output of this notebook becomes the foundation for model training in subsequent stages.